# Generated by Django 2.2.7 on 2019-11-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narwhals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('histologic_grade', models.IntegerField(default=0)),
                ('ml_prediction', models.FloatField(default=0.0)),
                ('pathology_report', models.TextField(default='HyperLink')),
                ('last_modified', models.DateField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patients', to='narwhals.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagefile', models.CharField(max_length=500)),
                ('ml_prediction', models.FloatField(default=0.0)),
                ('last_modified', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_image', to='narwhals.Patient')),
            ],
        ),
    ]
