# Generated by Django 2.2.7 on 2019-11-25 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narwhals', '0002_patient_patientimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patients', to='narwhals.Doctor'),
        ),
    ]
