# Generated by Django 2.2.7 on 2019-11-28 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narwhals', '0005_auto_20191127_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientimage',
            name='serverFilePath',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patients', to='narwhals.Doctor'),
        ),
    ]
