# Generated by Django 2.2.7 on 2019-11-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('narwhals', '0006_auto_20191127_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patients', to='narwhals.Doctor'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='imagefile',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='patientimage',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_image', to='narwhals.Patient'),
        ),
        migrations.CreateModel(
            name='PathologyScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pathology_Main_Img', models.ImageField(upload_to='images/')),
                ('ml_prediction', models.FloatField(default=0.0)),
                ('serverFilePath', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pathology_images', to='narwhals.Patient')),
            ],
        ),
    ]
